### ISSUE TITLE
Random Issues

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli-blueprint-test-helpers#1]
- [x] `ember-cli` should be in `devDependencies` (for both `ember-cli-blueprint-test-helpers` and `ember-cli-internal-test-helpers`) to prevent ending up with 2 or 3 nested ember-cli versions on npm 2.x.
- [x] A new blueprint for `ember-cli-blueprint-test-helpers` should be created that does the test infrastructure setup in https://github.com/ember-cli/ember-cli-blueprint-test-helpers/blob/master/blueprints/blueprint-test/index.js#L16-L2. This would allow for `ember install ember-cli-blueprint-test-helpers` to do that work once at install time. Currently, this is done for every new blueprint generated.
- [x] Last tagged & released version includes incorrect version numbers in blueprint, causing blueprint to fail.
- [ ] `-nodetest.js` file is generated in `blueprints/` directory, but I would expect it in `tests/blueprints/*-nodetest.js`...
- [ ] extra leading whitespace after `setupTestHooks` line in generated file
- [x] `setupTestHooks` line contains two semicolons (`;;`)

**Comment by trabus** [comment]
@rwjblue: regarding where the blueprint-test is generated, @stefanpenner suggested putting the blueprint tests in the same folder as the blueprint, modeled after pods. I'm fine moving it to `tests/blueprints/*`, but would like to discuss first.

**Comment by rwjblue** [comment]
Seems ok to include there, I honestly justThe only downsides with it are:

* it is *slightly* surprising (to the point where I thought it was a mistake). This can easily be fixed by some README tweaks. 
* it means the tests will be shipped to consumers (which is a thing we have tried to avoid in the past). This isn't a huge deal to me personally...

**Comment by stefanpenner** [comment]
> it means the tests will be shipped to consumers (which is a thing we have tried to avoid in the past). This isn't a huge deal to me personally...

.gitingore can prevent this, as long as it is easily matchable.

**Comment by rwjblue** [comment]
Ya, seems fine to me, just surprising that it was different than the norm.

**Comment by trabus** [comment]
> it means the tests will be shipped to consumers (which is a thing we have tried to avoid in the past). This isn't a huge deal to me personally...

Because the `blueprint-nodetest.js` file is not in the `files` folder, it is not copied when the blueprint generates.

**Comment by rwjblue** [comment]
@trabus - I was saying that these test files are shipped (aka included in the `node_modules` folder of the consuming app) to users of an addon that have `-nodetest.js` files in `blueprints`.

**Comment by trabus** [comment]
@rwjblue @stefanpenner any objection to using `*-nodetest.js` instead of `*-test.js`? Also I've essentially copied the runner from ember-cli and modified it to only look for the blueprint nodetests.

> @trabus - I was saying that these test files are shipped (aka included in the node_modules folder of the consuming app) to users of an addon that have -nodetest.js files in blueprints.
We could use an `.npmignore` file for that. In that case, maybe naming them all the same (like `blueprint-nodetest.js` or something ) would make that much easier.

**Comment by trabus** [comment]
This all appears to be resolved in the current state of blueprint-test-helpers.
