### ISSUE TITLE
Remove tmp-sync from dependencies

### ISSUE THREAD

**Issue by baweaver** [ember-cli/ember-cli-blueprint-test-helpers#105]
`tmp-sync` relies on an older version of lodash and is included transitively through other Ember projects as a result.

I'm currently investigating other options, but it appears that [tmp](https://github.com/raszi/node-tmp) may be a valid replacement ignoring the dependency on `os-tmp` which was deprecated for Node 4.x+ in favor of [os.tmpdir](https://nodejs.org/api/os.html#os_os_tmpdir)

I've submitted a [PR](https://github.com/kaelzhang/node-tmp-sync/pull/2) to tmp-sync to try and upgrade their dependency on [fs-sync](https://github.com/kaelzhang/node-fs-sync) which includes the older version of Lodash, but it's been without updates for a few years so I'm not optimistic that it sees the light of day.

Thanks for your time in reading!

**Comment by Turbo87** [comment]
since `tmp-sync` with your PR has been released I'm considering this issue fixed now
