### ISSUE TITLE
convert all code to node 4+ style

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli-blueprint-test-helpers#141]
const/let, function style, string templates.

Very good for new contributors.

**Comment by mbeatrizmagalhaes** [comment]
Hi! I'll work on this.

**Comment by kellyselden** [comment]
Awesome! One thing to note is that we tend to use const only for require statements, the rest we use let.

**Comment by mbeatrizmagalhaes** [comment]
Ok. I was using eslint no-var rule, which requires that all var that can be const, to be. I will then remove the eslint rule. 
Just to be sure, when you refer to function style, do you mean to use arrow callbacks ?

**Comment by kellyselden** [comment]
Arrow and object shorthand `xxx: function() {` -> `xxx() {`.
