### ISSUE TITLE
expect(...) is not complete

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli-blueprint-test-helpers#19]
https://github.com/ember-cli/ember-cli-blueprint-test-helpers/blob/master/lib/helpers/blueprint-helper.js#L189 is using `expect(foo);` but that itself won't throw any exceptions if `foo` is falsy. This should be changed to `expect(foo).is.ok;` or something similar.

**Comment by trabus** [comment]
Ah, good catch.  Will fix this tonight.
