### ISSUE TITLE
Asserting contents of `app/router.js`

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli-blueprint-test-helpers#38]
In the current state all asserted files are expected to be removed after the `destroy` command, but that makes it hard to assert the contents of `app/router.js`. We should probably introduce a `notDestroyed` flag or something like that.

**Comment by stefanpenner** [comment]
@ef4 made a cool little testing DSL for broccoli-uglify-sourcemap that may be appropriate here: https://github.com/ef4/broccoli-uglify-sourcemap/blob/master/test/test.js#L31-L34

**Comment by Turbo87** [comment]
looks good! although we could also think about using chai plugins instead.

**Comment by stefanpenner** [comment]
Yes
