### ISSUE TITLE
Move blueprint-test to node-tests folder

### ISSUE THREAD

**Issue by trabus** [ember-cli/ember-cli-blueprint-test-helpers#4]
To go with a more consistent structure for the tests, we should move the generated `blueprint-nodetest.js` in the blueprint-test blueprint to the `node-tests` folder.

- [x] create `node-tests` folder in blueprint-test blueprint files
- [x] change naming scheme from `blueprint-nodetest.js` to `[blueprintname]-test.js`
- [x] change `.npmignore` to ignore `node-tests` folder
- [x] change test runner to look into `node-tests` folder instead of looking for `-nodetest`
- [ ] move blueprint-tests in `ember-cli-legacy-blueprints` `to node-tests` folder

**Comment by rwjblue** [comment]
Reopened for the last item on the checklist (moving the files around in ember-cli-legacy-blueprints).

**Comment by trabus** [comment]
Working on that now. Thanks for reopening.

**Comment by trabus** [comment]
I have one more change, the blueprint tests were being generated in `node-tests/blueprints/blueprintname/blueprintname-test.js`, I'm moving it to `node-tests/blueprints/blueprintname-test.js`.

**Comment by trabus** [comment]
@rwjblue One thing I've found a bit annoying is blueprints with `-test` become `-test-test`, but it's only a minor annoyance.

**Comment by rwjblue** [comment]
LOL, that is kinda funny, but I think in its own way it makes sense...

**Comment by Turbo87** [comment]
@trabus I think since the test blueprints are also tested by the main blueprints we can just move the test blueprint tests into the main blueprint tests file.

**Comment by Turbo87** [comment]
closing this in favor of ember-cli/ember-cli-legacy-blueprints#2
