### ISSUE TITLE
generateFakePackageManifest() helper

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli-blueprint-test-helpers#83]
https://github.com/emberjs/data/pull/4691 introduced a new [`generateFakePackageManifest()`](https://github.com/emberjs/data/blob/master/node-tests/helpers/generate-fake-package-manifest.js) helper function that can be used to trick the `ember-cli-version-checker` module. I'd like to propose importing that helper function into this repository so that other users can benefit from it as well.

/cc @trabus @pangratz

**Comment by Turbo87** [comment]
@rwjblue should we put this in here? or would `ember-cli-version-checker` be a better location? or maybe both?

**Comment by trabus** [comment]
@Turbo87 what about putting it into [`ember-cli-internal-test-helpers`](https://github.com/ember-cli/ember-cli-internal-test-helpers)?

**Comment by Turbo87** [comment]
`ember-cli-internal-test-helpers` always sounds to me like it should only be used internally in Ember CLI and I suppose many others think of it the same way
